var BILD_MAPP2 = [
    ["ballImage", "./bilder/ball.png"],
    ["jumperBlueImage", "./bilder/jumperblue.png"],
    ["jumperGreenImage", "./bilder/jumpergreen.png"],
    ["foreground", "./bilder/backgroundSecondLayer.png"],
    ["clouds", "./bilder/clouds.png"],
    ["smoke", "./bilder/smoke.png"],
    ["exitButton", "./bilder/ExitButton.png"],
    ["winScreen", "./bilder/winScreen.png"],
    ["foregroundReal", "./bilder/background1v1.png"],
    ["buttonA", "./bilder/ui/multiplayerActiveButton.png"],
    ["buttonB", "./bilder/ui/multiplayerButton.png"],
    ["buttonC", "./bilder/ui/singleplayerActiveButton.png"],
    ["buttonD", "./bilder/ui/singleplayerButton.png"],
    ["buttonE", "./bilder/ui/trainingActiveButton.png"],
    ["buttonF", "./bilder/ui/trainingButton.png"],
];

var BILD_MAPP = [
    ["ballImage", "./bilder/ball.png"],
    ["jumperBlueImage", "./bilder/jumperblue.png"],
    ["jumperGreenImage", "./bilder/jumpergreen.png"],
    ["foreground", "./bilder/backgroundSecondLayer.png"],
    ["clouds", "./bilder/clouds.png"],
    ["smoke", "./bilder/smoke.png"],
    ["exitButton", "./bilder/ExitButton.png"],
    ["winScreen", "./bilder/winScreen.png"],
    ["foregroundReal", "./bilder/background1v1.png"],
    ["buttonA", "./bilder/ui/multiplayerActiveButton.png"],
    ["buttonB", "./bilder/ui/multiplayerButton.png"],
    ["buttonC", "./bilder/ui/singleplayerActiveButton.png"],
    ["buttonD", "./bilder/ui/singleplayerButton.png"],
    ["buttonE", "./bilder/ui/trainingActiveButton.png"],
    ["buttonF", "./bilder/ui/trainingButton.png"],
];